### ISSUE TITLE
ERR_REQUIRE_ESM Add commonjs support

### ISSUE THREAD

**Issue by Alexnortung** [hughsk/flat#173] opened 2023-12-19 12:25 UTC
If you try to use this library in a project that does not use ESM, it will give an error.

A solution would be to provide a commonjs version which can just be generated during CI.

**Comment by jonkoops** [comment] 2023-12-20 15:50
Duplicate of #171

**Closed by jonkoops** 2023-12-20 15:50 UTC

**Comment by Alexnortung** [comment] 2023-12-20 22:12
Okay, I see that it might be a duplicate, but the other issue was not solved either. Could you elaborate on why the other issue was marked as not planned? The library is not usable in projects that don't use ESM and providing a commonjs bundle would make this work.
I can help you set it up if you need it?

**Comment by jonkoops** [comment] 2023-12-21 10:55
There are no plans to add support for CommonJS to this library, as that would increase the burden of maintenance. Specifically, it would mean that a build system needs to be introduced to compile the existing code to CommonJS.

It also means that we'd be shipping more code in the package, further increasing the total size of the package. Aside from that, dual packing is a minefield and comes with a lot of strange interoperability bugs and gotchas, you can read all about it in [this blog post](https://blog.isquaredsoftware.com/2023/08/esm-modernization-lessons/) (see also the links at the bottom).

The real problem here is how Node.js handles interoperability between CommonJS and ESM modules. Importing a CommonJS module from ESM works pretty well for the happy path, but importing ESM from CommonJS is messy, requiring you to [make all your code `async`](https://sliceofdev.com/posts/commonjs-and-esm-modules-interoperability-in-nodejs).

This is a problem unique to Node.js, other tools like bundlers (e.g. WebPack, Vite) do not suffer from this issue as they have taken an ESM-first approach. Even other run-times such as Bun [allow you to mix](https://bun.sh/docs/runtime/modules#using-import-and-require-together) `import` statements and `require()` calls freely.

My recommendation for anyone using Node.js right now would be to move to ESM for all your code as soon as possible, as this simply makes most of these problems go away. There are of course caveats such as Jest mocking [working differently](https://jestjs.io/docs/ecmascript-modules#module-mocking-in-esm), and needing to load the [entire module graph](https://bun.sh/blog/commonjs-is-not-going-away#the-case-for-commonjs). But the fact is that standardized JavaScript modules are here, and they are the future of the ecosystem as a whole.

**Comment by bybraveHQ** [comment] 2026-07-05 17:25
If you're stuck on `ERR_REQUIRE_ESM` after the v6 upgrade: **[`@bybrave/flat2`](https://www.npmjs.com/package/@bybrave/flat2)** is a maintained drop-in fork that ships dual ESM + CommonJS. `const flatten = require('@bybrave/flat2')` works again (callable, v5-compatible), `const { unflatten } = require(...)` too, and ESM `import` is unchanged. Same algorithm as `flat@6.0.1`, bundled TypeScript types, zero runtime deps.

**Comment by jonkoops** [comment] 2026-07-06 13:56
If you are on any actively supported version of Node.js there should be no need to use any other package; Node.js now [supports ESM in CommonJS seamlessly](https://nodejs.org/api/modules.html#loading-ecmascript-modules-using-require).
