### ISSUE TITLE
Supported char sets

### ISSUE THREAD

**Issue by seneschal2** [hughsk/flat#40] opened 2016-03-08 16:51 UTC
What character sets are supported?  Seems to abort with words like "apéritif"

**Comment by richardschneider** [comment] 2016-08-16 04:45
Could you give an example? What do you mean by `abort` (stack trace would help)

**Comment by jonkoops** [comment] 2022-08-26 16:24
Closing this due to lack of responsiveness from the author. I am not able to reproduce this.

**Closed by jonkoops** 2022-08-26 16:24 UTC
