### ISSUE TITLE
Inconsistent behavior according to the node version

### ISSUE THREAD

**Issue by wutu** [hughsk/flat#45] opened 2016-04-25 17:58 UTC
Hello, if I use this:

```
message = 20
try data = flatten JSON.parse(message)
```

on Node v0.10.26 returns "undefined"
on Node v4.4.1 returns "{}"

**Comment by schang933** [comment] 2016-04-30 18:41
Similar issue:
Upgraded from Node v5.10.1 to v6.0.0 and flat doesn't seem to play well with AWS. Works as intended after downgrading to v5.11.0. General idea of code below. AWS API call is [here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html#update-property).

```javascript
var flattened = flat(someObject, { maxDepth: N });
var values = {};
var count = 0;
for (var field in flattened) {
  values[":v" + count] = flattened[field];
  count += 1;
}
var params = {
  // ... stuff for AWS
  ExpressionAttributeValues: values,
  // ... more stuff for AWS
}
logger.info(params); // no issues logging the object
aDynamoDBObject.update(params); // AWS error: ExpressionAttributeValues must not be empty
```

It seems like the reference to the flattened object's value is lost. Tried using the [deepcopy](https://github.com/sasaplus1/deepcopy.js) library to no avail. Works as intended after replacing

```javascript
flattened[field]
```

with

```javascript
Object.assign({}, flattened[field])
```

But this doesn't work when flattened[field] is not an object.

**Comment by jonkoops** [comment] 2022-08-26 16:25
Closing this as the issue was reported for currently ancient versions of Node.js and it is no longer possible to reproduce this. As far as I can tell this behavior is consistent in modern version of Node.js.

**Closed by jonkoops** 2022-08-26 16:25 UTC
